# Generated by Django 5.1 on 2025-11-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleado', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('id_atr', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('altura_min', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_emp', models.IntegerField()),
            ],
        ),
    ]
