# Generated by Django 5.1 on 2025-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleado', '0003_atraccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_atr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
