# Generated by Django 5.1 on 2025-11-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleado', '0004_alter_cliente_id_atr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraccion',
            name='altura_min',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='atraccion',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='atraccion',
            name='id_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_atr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
