# Generated by Django 5.1 on 2025-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleado', '0005_alter_atraccion_altura_min_alter_atraccion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraccion',
            name='id_emp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
